<a href="https://colab.research.google.com/github/mtareqsoliman/yap506_MatYon/blob/main/YapiSistHesabMatYon_Odev3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import scipy.special as ssp
import sympy as sym

# Enter no. of element
n_el = 12

# Enter no. of nodes
n_nd = 10


K_global = np.zeros((n_nd*3,n_nd*3)) # Global stiffness matrix is created

nodes_list = pd.DataFrame(data=None, columns=['x_coord','z_coord'], index=np.arange(1,n_nd+1,1))
rstrd_list = pd.DataFrame(data=None, columns=['Rstrd_theta','Rstrd_x','Rstrd_z'], index=np.arange(1,n_nd+1,1))
spring_list = pd.DataFrame(data=None, columns=['Yay_theta','Yay_x','Yay_z'], index=np.arange(1,n_el+1,1))
pntfr_list = pd.DataFrame(data=np.zeros((n_nd,3),dtype='int'), columns=['P_theta','P_x','P_z'], index=np.arange(1,n_nd+1,1))
dstfr_list = pd.DataFrame(data=np.zeros((n_el,2),dtype='int'), columns=['W_x','W_z'], index=np.arange(1,n_el+1,1))
ele_list = pd.DataFrame(data=None, columns=['node_i','node_j','Length','beta','EI','EF'], index=np.arange(1,n_el+1,1))
deform_list = pd.DataFrame(data=np.zeros((n_nd,3),dtype='int'), columns=['Δ_rot','Δ_x','Δ_z'], index=np.arange(1,n_nd+1,1))


# Enter Stiffness properties
EI_global = 100000
EF_global = 10000000

# Enter nodes coordinates
nodes_list.loc[1] = [0,16]
nodes_list.loc[2] = [4,16]
nodes_list.loc[3] = [0,13]
nodes_list.loc[4] = [4,13]
nodes_list.loc[5] = [0,10]
nodes_list.loc[6] = [4,10]
nodes_list.loc[7] = [0,7]
nodes_list.loc[8] = [4,7]
nodes_list.loc[9] = [0,4]
nodes_list.loc[10] = [4,4]

# Enter elements   i-j-L-β-   EI-       EF
ele_list.loc[1] = [1,2,4,0,EI_global,EF_global]
ele_list.loc[2] = [3,1,3,270,EI_global,EF_global]
ele_list.loc[3] = [4,2,3,270,EI_global,EF_global]

ele_list.loc[4] = [3,4,4,0,EI_global,EF_global]
ele_list.loc[5] = [5,3,3,270,EI_global,EF_global]
ele_list.loc[6] = [6,4,3,270,EI_global,EF_global]

ele_list.loc[7] = [5,6,4,0,EI_global,EF_global]
ele_list.loc[8] = [7,5,3,270,EI_global,EF_global]
ele_list.loc[9] = [6,8,3,270,EI_global,EF_global]

ele_list.loc[10] = [7,8,4,0,EI_global,EF_global]
ele_list.loc[11] = [9,7,3,270,EI_global,EF_global]
ele_list.loc[12] = [10,8,3,270,EI_global,EF_global]



# Enter Applied point loads
pntfr_list.loc[1] = [0,100,0]
pntfr_list.loc[2] = [0,0,0]
pntfr_list.loc[3] = [0,0,0]
pntfr_list.loc[4] = [0,0,0]
pntfr_list.loc[5] = [0,0,0]
pntfr_list.loc[6] = [0,0,0]
pntfr_list.loc[7] = [0,0,0]
pntfr_list.loc[8] = [0,0,0]
pntfr_list.loc[9] = [0,0,0]
pntfr_list.loc[10] = [0,0,0]


# Enter boundary conditions (restrained)
rstrd_list.loc[1] = [0,0,0]
rstrd_list.loc[2] = [0,0,0]
rstrd_list.loc[3] = [0,0,0]
rstrd_list.loc[4] = [0,0,0]
rstrd_list.loc[5] = [0,0,0]
rstrd_list.loc[6] = [0,0,0]
rstrd_list.loc[7] = [0,0,0]
rstrd_list.loc[8] = [0,0,0]
rstrd_list.loc[9] = [1,1,1]
rstrd_list.loc[10] = [1,1,1]

rstrd = np.array(rstrd_list).flatten() # try ravel also


# Enter elastic hinge locations (springs)
spring_list.loc[1] = np.array([10**50,10**50,10**50])
spring_list.loc[2] = np.array([10**50,10**50,10**50])
spring_list.loc[3] = np.array([10**50,10**50,10**50])
spring_list.loc[4] = np.array([10**50,10**50,10**50])
spring_list.loc[5] = np.array([10**50,10**50,10**50])
spring_list.loc[6] = np.array([10**50,10**50,10**50])
spring_list.loc[7] = np.array([10**50,10**50,10**50])
spring_list.loc[8] = np.array([10**50,10**50,10**50])
spring_list.loc[9] = np.array([10**50,10**50,10**50])
spring_list.loc[10] = np.array([10**50,10**50,10**50])


# Enter Applied distributed loads
dstfr_list.loc[1] = [0,0]
dstfr_list.loc[2] = [0,0]
dstfr_list.loc[3] = [0,0]
dstfr_list.loc[4] = [0,0]
dstfr_list.loc[5] = [0,0]
dstfr_list.loc[6] = [0,0]
dstfr_list.loc[7] = [0,0]
dstfr_list.loc[8] = [0,0]
dstfr_list.loc[9] = [0,0]
dstfr_list.loc[10] = [0,0]
dstfr_list.loc[11] = [0,0]
dstfr_list.loc[12] = [0,0]

# Enter sıcaklık değişmesi parameters
#tmprt_list.loc[1] =
deform_list.loc[1] = [0,0,0]
deform_list.loc[2] = [0,0,0]
deform_list.loc[3] = [0,0,0]
deform_list.loc[4] = [0,0,0]
deform_list.loc[5] = [0,0,0]
deform_list.loc[6] = [0,0,0]
deform_list.loc[7] = [0,0,0]
deform_list.loc[8] = [0,0,0]
deform_list.loc[9] = [0,0,0]
deform_list.loc[10] = [0,0,0]

deform = np.array(deform_list).flatten()

p0_global = np.zeros((n_nd*3,1))

q_global = np.array(pntfr_list).reshape(n_nd*3,1)

#for ele in np.arange(1,n_el+1,1):
for ele in np.arange(1,n_el+1,1):
  i = ele_list.loc[ele]['node_i']
  j = ele_list.loc[ele]['node_j']
  EI = ele_list.loc[ele]['EI']
  EF = ele_list.loc[ele]['EF']
  beta = ele_list.loc[ele]['beta']
  L = ele_list.loc[ele]['Length']
  L_x = L*ssp.cosdg(beta)
  L_z = L*ssp.sindg(beta)

  # distributed load
  W_x = dstfr_list.loc[ele]['W_x']
  W_z = dstfr_list.loc[ele]['W_z']

  ## point load
  Pl_M_i,Pl_M_j = pntfr_list.loc[i]['P_theta'],pntfr_list.loc[j]['P_theta']
  Pl_x_i,Pl_x_j = pntfr_list.loc[i]['P_x'],pntfr_list.loc[j]['P_x']
  Pl_z_i,Pl_z_j = pntfr_list.loc[i]['P_z'],pntfr_list.loc[j]['P_z']


  ## deformation due to settlement
  dfrm_theta_i,dfrm_x_i,dfrm_z_i = deform_list.loc[i]['Δ_rot'],deform_list.loc[i]['Δ_x'],deform_list.loc[i]['Δ_z']
  dfrm_theta_j,dfrm_x_j,dfrm_z_j = deform_list.loc[j]['Δ_rot'],deform_list.loc[j]['Δ_x'],deform_list.loc[j]['Δ_z']


  K_ii = np.matrix(([[4*EI/L,0,6*EI/L**2],
                       [0,EF/L,0],
                       [6*EI/L**2,0,12*EI/L**3]]))

  K_jj = np.matrix(([[4*EI/L,0,6*EI/L**2],
                       [0,EF/L,0],
                       [6*EI/L**2,0,12*EI/L**3]]))
  print('K_{}{}_ii ='.format(i,j))
  display(sym.Matrix(K_ii))

  K_ij = np.matrix(([[2*EI/L,0,6*EI/L**2],
                        [0,EF/L,0],
                        [6*EI/L**2,0,12*EI/L**3]]))

  print('K_{}{}_ij ='.format(i,j))
  display(sym.Matrix(K_ij))


  K1_ii = np.float64(K_ii+np.diag(spring_list.loc[i]))
  K1_jj = np.float64(K_jj+np.diag(spring_list.loc[j]))
  K1_ij = np.float64(K_ij)
  K1_ji = K1_ij

  K0 = np.vstack((np.hstack((K_ii,K_ij)),np.hstack((K_ij,K_jj))))
  K1 = np.vstack((np.hstack((K1_ii,K1_ij)),np.hstack((K1_ji,K1_jj))))
  K_lokal = K0-np.dot(np.dot(K0,np.linalg.inv(K1)),K0)
  print('K_{}{}_LOKAL ='.format(i,j))
  display(sym.Matrix(K_lokal))
  K_ii, K_ij, K_ji, K_jj =  K_lokal[0:3,0:3],K_lokal[0:3,3:6],K_lokal[3:6,0:3],K_lokal[3:6,3:6]

  #K_1 = np.diag(np.full((6, 6), 10**50))
  #K_1[np.]

  T2_i = np.matrix(([[1,0,0],
                       [0,-ssp.cosdg(beta),ssp.sindg(beta)],
                       [0,-ssp.sindg(beta),-ssp.cosdg(beta)]]))

  T2_j = np.matrix(([[1,0,0],
                       [0,ssp.cosdg(beta),-ssp.sindg(beta)],
                       [0,ssp.sindg(beta),ssp.cosdg(beta)]]))

  print('T_2_{} ='.format(ele))
  T_2 =  np.vstack((np.hstack((T2_i,np.zeros((3,3)))),np.hstack((np.zeros((3,3)),T2_j))))
  display(sym.Matrix(T_2))

  # Calculating FEM from distributed load
  p0_dst = np.transpose(np.matrix([-W_x*L_z**2/12+W_z*L_x**2/12,
                               W_x*L_x/2+W_z*L_z/2,
                               W_x*L_z/2+W_z*L_x/2,
                               W_x*L_x**2/12-W_z*L_x**2/12+Pl_M_j,
                              -W_x*L_x/2-W_z*L_z/2,
                              -W_x*L_z/2-W_z*L_x/2]))
  p0_indrgnms = p0_dst-np.dot(np.dot(K0,np.linalg.inv(K1)),p0_dst)

  # calculating P from deformation
  w_dfrm = np.transpose(np.hstack((deform_list.loc[i],deform_list.loc[j])))
  print('w_dfrm_{} ='.format(ele))
  print(w_dfrm)

  p0_dfrm = np.dot(np.dot(np.dot(T_2,K_lokal),np.transpose(T_2)),np.transpose(w_dfrm))
  p0 = p0_indrgnms+p0_dfrm
  p0_transf = p0

  p0_global[(i-1)*3] =     p0_transf[0,0]+p0_global[(i-1)*3]
  p0_global[((i-1)*3)+1] = p0_transf[0,1]+p0_global[((i-1)*3)+1]
  p0_global[((i-1)*3)+2] = p0_transf[0,2]+p0_global[((i-1)*3)+2]
  p0_global[(j-1)*3] =     p0_transf[0,3]+p0_global[(j-1)*3]
  p0_global[((j-1)*3)+1] = p0_transf[0,4]+p0_global[((j-1)*3)+1]
  p0_global[((j-1)*3)+2] = p0_transf[0,5]+p0_global[((j-1)*3)+2]

  print('―' * 50)


  K_global[3*(i-1):3*(i-1)+3,3*(i-1):3*(i-1)+3] = np.dot(np.dot(T2_i,K_ii),np.transpose(T2_i))+K_global[3*(i-1):3*(i-1)+3,3*(i-1):3*(i-1)+3]
  K_global[3*(i-1):3*(i-1)+3,3*(j-1):3*(j-1)+3] = np.dot(np.dot(T2_i,K_ij),np.transpose(T2_j))+K_global[3*(i-1):3*(i-1)+3,3*(j-1):3*(j-1)+3]
  K_global[3*(j-1):3*(j-1)+3,3*(i-1):3*(i-1)+3] = np.dot(np.dot(T2_j,K_ji),np.transpose(T2_i))+K_global[3*(j-1):3*(j-1)+3,3*(i-1):3*(i-1)+3]
  K_global[3*(j-1):3*(j-1)+3,3*(j-1):3*(j-1)+3] = np.dot(np.dot(T2_j,K_jj),np.transpose(T2_j))+K_global[3*(j-1):3*(j-1)+3,3*(j-1):3*(j-1)+3]

  display(sym.Matrix(K_global))
  display(sym.Matrix(p0_global))


  ### force vector
  #p0[i-1:i+2] = [-dstfr_list.loc[ele]['W_x']+dstfr_list.loc[ele]['W_z']+pntfr_list.loc[ele]['P_theta']]

P_global = q_global-p0_global


## trimming the equation
trim_index = np.flatnonzero(rstrd)
K_global_trimmed = np.delete(np.delete(K_global,trim_index,0),trim_index,1)

p0_global_trimmed = np.delete(p0_global,trim_index,0)
q_global_trimmed = np.delete(q_global,trim_index,0)


d = np.linalg.solve(K_global_trimmed,q_global_trimmed-p0_global_trimmed)
display(sym.Matrix(d))
print(d)

print('K_global_trimmed')

K11 = K_global[:24,:24]
K12 = K_global[:24,24:]
K21 = K_global[24:,:24]
K22 = K_global[24:,24:]
Q1 = q_global[:24]
Q2 = q_global[24:]

#Dd =

K_star = K22-np.dot(np.dot(K21,np.linalg.inv(K11)),K12)
P_star = Q2-np.dot(np.dot(K21,np.linalg.inv(K11)),Q1)
#D_i = np.dot(np.inverse(K11),Q1)-np.dot(np.dot(np.inverse(K11),K12),Dd)

display(sym.Matrix(K_star))

K_star_11,K_star_12,K_star_21,K_star_22 = K_star[:3,:3],K_star[:3,3:],K_star[3:,:3],K_star[3:,3:]
P_star_11,P_star_12,P_star_21,P_star_22 = P_star[:3,:3],P_star[:3,3:],P_star[3:,:3],P_star[3:,3:]

P_star

K_12_ii =


Matrix([
[100000.0,         0, 37500.0],
[       0, 2500000.0,       0],
[ 37500.0,         0, 18750.0]])

K_12_ij =


Matrix([
[50000.0,         0, 37500.0],
[      0, 2500000.0,       0],
[37500.0,         0, 18750.0]])

K_12_LOKAL =


Matrix([
[100000.0,         0, 37500.0,  50000.0,         0, 37500.0],
[       0, 2500000.0,       0,        0, 2500000.0,       0],
[ 37500.0,         0, 18750.0,  37500.0,         0, 18750.0],
[ 50000.0,         0, 37500.0, 100000.0,         0, 37500.0],
[       0, 2500000.0,       0,        0, 2500000.0,       0],
[ 37500.0,         0, 18750.0,  37500.0,         0, 18750.0]])

T_2_1 =


Matrix([
[1.0,    0,    0,   0,   0,   0],
[  0, -1.0,    0,   0,   0,   0],
[  0,    0, -1.0,   0,   0,   0],
[  0,    0,    0, 1.0,   0,   0],
[  0,    0,    0,   0, 1.0,   0],
[  0,    0,    0,   0,   0, 1.0]])

w_dfrm_1 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[100000.0,          0, -37500.0,  50000.0,          0,  37500.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[       0,  2500000.0,        0,        0, -2500000.0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[-37500.0,          0,  18750.0, -37500.0,          0, -18750.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 50000.0,          0, -37500.0, 100000.0,          0,  37500.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[       0, -2500000.0,        0,        0,  2500000.0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 37500.0,          0, -18750.0,  37500.0,          0,  18750.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[       0,          0,        0,        0,          0,        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[       0,          0,   

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_31_ii =


Matrix([
[133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_31_ij =


Matrix([
[66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_31_LOKAL =


Matrix([
[133333.333333333,                0, 66666.6666666667, 66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444],
[66666.6666666667,                0, 66666.6666666667, 133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444]])

T_2_2 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_2 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,  50000.0,          0,  37500.0,  66666.6666666667, -66666.6666666667,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,        0, -2500000.0,        0,  66666.6666666667, -44444.4444444444,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0,  3352083.33333333, -37500.0,          0, -18750.0,                 0,                 0, -3333333.33333333, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[          50000.0,                 0,          -37500.0, 100000.0,          0,  37500.0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[                0,        -2500000.0,                 0,        0,  2500000.0,        0,                 0,                 0,                 0, 

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_42_ii =


Matrix([
[133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_42_ij =


Matrix([
[66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_42_LOKAL =


Matrix([
[133333.333333333,                0, 66666.6666666667, 66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444],
[66666.6666666667,                0, 66666.6666666667, 133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444]])

T_2_3 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_3 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0,  3352083.33333333,          -37500.0,                 0,          -18750.0,                 0,                 0, -3333333.33333333,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[          50000.0,                 0,          -37500.0,  233333.333333333,  66666.6666666667,           37500.0,                 0,      

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_34_ii =


Matrix([
[100000.0,         0, 37500.0],
[       0, 2500000.0,       0],
[ 37500.0,         0, 18750.0]])

K_34_ij =


Matrix([
[50000.0,         0, 37500.0],
[      0, 2500000.0,       0],
[37500.0,         0, 18750.0]])

K_34_LOKAL =


Matrix([
[100000.0,         0, 37500.0,  50000.0,         0, 37500.0],
[       0, 2500000.0,       0,        0, 2500000.0,       0],
[ 37500.0,         0, 18750.0,  37500.0,         0, 18750.0],
[ 50000.0,         0, 37500.0, 100000.0,         0, 37500.0],
[       0, 2500000.0,       0,        0, 2500000.0,       0],
[ 37500.0,         0, 18750.0,  37500.0,         0, 18750.0]])

T_2_4 =


Matrix([
[1.0,    0,    0,   0,   0,   0],
[  0, -1.0,    0,   0,   0,   0],
[  0,    0, -1.0,   0,   0,   0],
[  0,    0,    0, 1.0,   0,   0],
[  0,    0,    0,   0, 1.0,   0],
[  0,    0,    0,   0,   0, 1.0]])

w_dfrm_4 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0,  3352083.33333333,          -37500.0,                 0,          -18750.0,                 0,                 0, -3333333.33333333,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[          50000.0,                 0,          -37500.0,  233333.333333333,  66666.6666666667,           37500.0,                 0,      

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_53_ii =


Matrix([
[133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_53_ij =


Matrix([
[66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_53_LOKAL =


Matrix([
[133333.333333333,                0, 66666.6666666667, 66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444],
[66666.6666666667,                0, 66666.6666666667, 133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444]])

T_2_5 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_5 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0,  3352083.33333333,          -37500.0,                 0,          -18750.0,                 0,                 0, -3333333.33333333,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_64_ii =


Matrix([
[133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_64_ij =


Matrix([
[66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_64_LOKAL =


Matrix([
[133333.333333333,                0, 66666.6666666667, 66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444],
[66666.6666666667,                0, 66666.6666666667, 133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444]])

T_2_6 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_6 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0,  3352083.33333333,          -37500.0,                 0,          -18750.0,                 0,                 0, -3333333.33333333,                 0,                 0,                 0,   

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_56_ii =


Matrix([
[100000.0,         0, 37500.0],
[       0, 2500000.0,       0],
[ 37500.0,         0, 18750.0]])

K_56_ij =


Matrix([
[50000.0,         0, 37500.0],
[      0, 2500000.0,       0],
[37500.0,         0, 18750.0]])

K_56_LOKAL =


Matrix([
[100000.0,         0, 37500.0,  50000.0,         0, 37500.0],
[       0, 2500000.0,       0,        0, 2500000.0,       0],
[ 37500.0,         0, 18750.0,  37500.0,         0, 18750.0],
[ 50000.0,         0, 37500.0, 100000.0,         0, 37500.0],
[       0, 2500000.0,       0,        0, 2500000.0,       0],
[ 37500.0,         0, 18750.0,  37500.0,         0, 18750.0]])

T_2_7 =


Matrix([
[1.0,    0,    0,   0,   0,   0],
[  0, -1.0,    0,   0,   0,   0],
[  0,    0, -1.0,   0,   0,   0],
[  0,    0,    0, 1.0,   0,   0],
[  0,    0,    0,   0, 1.0,   0],
[  0,    0,    0,   0,   0, 1.0]])

w_dfrm_7 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0,  3352083.33333333,          -37500.0,                 0,          -18750.0,                 0,                 0, -3333333.33333333,                 0,                 0,                 0,   

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_75_ii =


Matrix([
[133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_75_ij =


Matrix([
[66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_75_LOKAL =


Matrix([
[133333.333333333,                0, 66666.6666666667, 66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444],
[66666.6666666667,                0, 66666.6666666667, 133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444]])

T_2_8 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_8 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0,  3352083.33333333,          -37500.0,                 0,          -18750.0,                 0,  

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_68_ii =


Matrix([
[133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_68_ij =


Matrix([
[66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_68_LOKAL =


Matrix([
[133333.333333333,                0, 66666.6666666667, 66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444],
[66666.6666666667,                0, 66666.6666666667, 133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444]])

T_2_9 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_9 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0, 

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_78_ii =


Matrix([
[100000.0,         0, 37500.0],
[       0, 2500000.0,       0],
[ 37500.0,         0, 18750.0]])

K_78_ij =


Matrix([
[50000.0,         0, 37500.0],
[      0, 2500000.0,       0],
[37500.0,         0, 18750.0]])

K_78_LOKAL =


Matrix([
[100000.0,         0, 37500.0,  50000.0,         0, 37500.0],
[       0, 2500000.0,       0,        0, 2500000.0,       0],
[ 37500.0,         0, 18750.0,  37500.0,         0, 18750.0],
[ 50000.0,         0, 37500.0, 100000.0,         0, 37500.0],
[       0, 2500000.0,       0,        0, 2500000.0,       0],
[ 37500.0,         0, 18750.0,  37500.0,         0, 18750.0]])

T_2_10 =


Matrix([
[1.0,    0,    0,   0,   0,   0],
[  0, -1.0,    0,   0,   0,   0],
[  0,    0, -1.0,   0,   0,   0],
[  0,    0,    0, 1.0,   0,   0],
[  0,    0,    0,   0, 1.0,   0],
[  0,    0,    0,   0,   0, 1.0]])

w_dfrm_10 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0, 0, 0, 0],
[         -37500.0,                 0, 

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_97_ii =


Matrix([
[133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_97_ij =


Matrix([
[66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_97_LOKAL =


Matrix([
[133333.333333333,                0, 66666.6666666667, 66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444],
[66666.6666666667,                0, 66666.6666666667, 133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444]])

T_2_11 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_11 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 0, 0, 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,           

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_108_ii =


Matrix([
[133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_108_ij =


Matrix([
[66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444]])

K_108_LOKAL =


Matrix([
[133333.333333333,                0, 66666.6666666667, 66666.6666666667,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444],
[66666.6666666667,                0, 66666.6666666667, 133333.333333333,                0, 66666.6666666667],
[               0, 3333333.33333333,                0,                0, 3333333.33333333,                0],
[66666.6666666667,                0, 44444.4444444444, 66666.6666666667,                0, 44444.4444444444]])

T_2_12 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_12 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 233333.333333333,  66666.6666666667,          -37500.0,           50000.0,                 0,           37500.0,  66666.6666666667, -66666.6666666667,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0],
[ 66666.6666666667,  2544444.44444444,                 0,                 0,        -2500000.0,                 0,  66666.6666666667, -44444.4444444444,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0,                 0, 

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

Matrix([
[-0.000654759257799521],
[   0.0100722782288764],
[-0.000121141918070647],
[-0.000579801182404193],
[   0.0100539938886648],
[ 0.000121141918070646],
[-0.000773157762951326],
[  0.00670889683465311],
[ -0.00010861595969665],
[-0.000971786026851148],
[  0.00669811893787883],
[ 0.000108615959696649],
[-0.000750812622634009],
[  0.00380769208673097],
[  -7.7681313233962e-5],
[ 0.000132010247756696],
[  0.00380370443878124],
[  7.76813132339619e-5],
[-0.000595720739975429],
[  0.00139694807044503],
[ -4.06590548277867e-5],
[ 0.000231790892115515],
[  0.00139894670134476],
[  4.06590548277867e-5]])

[[-6.54759258e-04]
 [ 1.00722782e-02]
 [-1.21141918e-04]
 [-5.79801182e-04]
 [ 1.00539939e-02]
 [ 1.21141918e-04]
 [-7.73157763e-04]
 [ 6.70889683e-03]
 [-1.08615960e-04]
 [-9.71786027e-04]
 [ 6.69811894e-03]
 [ 1.08615960e-04]
 [-7.50812623e-04]
 [ 3.80769209e-03]
 [-7.76813132e-05]
 [ 1.32010248e-04]
 [ 3.80370444e-03]
 [ 7.76813132e-05]
 [-5.95720740e-04]
 [ 1.39694807e-03]
 [-4.06590548e-05]
 [ 2.31790892e-04]
 [ 1.39894670e-03]
 [ 4.06590548e-05]]
K_global_trimmed


Matrix([
[ 70800.0762002089,  -22713.348764161, -2960.96389401337, -41117.8188232464,  22713.3487641596,  2960.96389401337],
[ -22713.348764161,  11641.8866574482, -57.8102890519372,  22689.5411859788, -11641.8866574475,  57.8102890519378],
[-2960.96389401337, -57.8102890519378,  22556.4418412657, -3200.61014854414,  57.8102890518658, -22556.4418412671],
[-41117.8188232464,  22689.5411859788, -3200.61014854414,  70701.3844788207, -22689.5411859806,  3200.61014854413],
[ 22713.3487641596, -11641.8866574475,  57.8102890518644, -22689.5411859806,  11641.8866574487, -57.8102890518585],
[ 2960.96389401336,    57.81028905194, -22556.4418412671,  3200.61014854412, -57.8102890518557,  22556.4418412666]])

array([[ -53.41515536],
       [  22.37186491],
       [-135.53018276],
       [-108.71583956],
       [  77.62813509],
       [ 135.53018276]])

In [2]:
import pandas as pd
import numpy as np
import scipy.special as ssp
import sympy as sym

# Enter no. of element
n_el = 4

# Enter no. of nodes
n_nd = 4


K_global = np.zeros((n_nd*3,n_nd*3)) # Global stiffness matrix is created

nodes_list = pd.DataFrame(data=None, columns=['x_coord','z_coord'], index=np.arange(1,n_nd+1,1))
rstrd_list = pd.DataFrame(data=None, columns=['Rstrd_theta','Rstrd_x','Rstrd_z'], index=np.arange(1,n_nd+1,1))
spring_list = pd.DataFrame(data=None, columns=['Yay_theta','Yay_x','Yay_z'], index=np.arange(1,n_el+1,1))
pntfr_list = pd.DataFrame(data=np.zeros((n_nd,3),dtype='int'), columns=['P_theta','P_x','P_z'], index=np.arange(1,n_nd+1,1))
dstfr_list = pd.DataFrame(data=np.zeros((n_el,2),dtype='int'), columns=['W_x','W_z'], index=np.arange(1,n_el+1,1))
ele_list = pd.DataFrame(data=None, columns=['node_i','node_j','Length','beta','EI','EF'], index=np.arange(1,n_el+1,1))
deform_list = pd.DataFrame(data=np.zeros((n_nd,3),dtype='int'), columns=['Δ_rot','Δ_x','Δ_z'], index=np.arange(1,n_nd+1,1))


# Enter Stiffness properties
EI_global = 500000
EF_global = 50000000

# Enter nodes coordinates
nodes_list.loc[1] = [0,4]
nodes_list.loc[2] = [4,4]
nodes_list.loc[3] = [0,0]
nodes_list.loc[4] = [4,0]


# Enter elements   i-j-L-β-   EI-       EF
ele_list.loc[1] = [1,2,4,0,EI_global,EF_global]
ele_list.loc[2] = [3,1,3,270,EI_global,EF_global]
ele_list.loc[3] = [4,2,3,270,EI_global,EF_global]
ele_list.loc[4] = [3,4,4,0,EI_global,EF_global]


# Enter Applied point loads
pntfr_list.loc[1] = [0,0,0]
pntfr_list.loc[2] = [0,0,0]
pntfr_list.loc[3] = [0,0,0]
pntfr_list.loc[4] = [0,0,0]

# Enter boundary conditions (restrained)
rstrd_list.loc[1] = [0,1,0]
rstrd_list.loc[2] = [0,0,0]
rstrd_list.loc[3] = [0,0,1]
rstrd_list.loc[4] = [0,0,1]

rstrd = np.array(rstrd_list).flatten() # try ravel also


# Enter elastic hinge locations (springs)
spring_list.loc[1] = np.array([10**50,10**50,10**50])
spring_list.loc[2] = np.array([10**50,10**50,10**50])
spring_list.loc[3] = np.array([10**50,10**50,10**50])
spring_list.loc[4] = np.array([10**50,10**50,10**50])


# Enter Applied distributed loads
dstfr_list.loc[1] = [0,0]
dstfr_list.loc[2] = [0,0]
dstfr_list.loc[3] = [0,0]
dstfr_list.loc[4] = [0,0]


# Enter sıcaklık değişmesi parameters
#tmprt_list.loc[1] =
deform_list.loc[1] = [0,0,0]
deform_list.loc[2] = [0,0,0]
deform_list.loc[3] = [0,0,0]
deform_list.loc[4] = [0,0,0]

deform = np.array(deform_list).flatten()

p0_global = np.zeros((n_nd*3,1))

q_global = np.array(pntfr_list).reshape(n_nd*3,1)

#for ele in np.arange(1,n_el+1,1):
for ele in np.arange(1,n_el+1,1):
  i = ele_list.loc[ele]['node_i']
  j = ele_list.loc[ele]['node_j']
  EI = ele_list.loc[ele]['EI']
  EF = ele_list.loc[ele]['EF']
  beta = ele_list.loc[ele]['beta']
  L = ele_list.loc[ele]['Length']
  L_x = L*ssp.cosdg(beta)
  L_z = L*ssp.sindg(beta)

  # distributed load
  W_x = dstfr_list.loc[ele]['W_x']
  W_z = dstfr_list.loc[ele]['W_z']

  ## point load
  Pl_M_i,Pl_M_j = pntfr_list.loc[i]['P_theta'],pntfr_list.loc[j]['P_theta']
  Pl_x_i,Pl_x_j = pntfr_list.loc[i]['P_x'],pntfr_list.loc[j]['P_x']
  Pl_z_i,Pl_z_j = pntfr_list.loc[i]['P_z'],pntfr_list.loc[j]['P_z']


  ## deformation due to settlement
  dfrm_theta_i,dfrm_x_i,dfrm_z_i = deform_list.loc[i]['Δ_rot'],deform_list.loc[i]['Δ_x'],deform_list.loc[i]['Δ_z']
  dfrm_theta_j,dfrm_x_j,dfrm_z_j = deform_list.loc[j]['Δ_rot'],deform_list.loc[j]['Δ_x'],deform_list.loc[j]['Δ_z']


  K_ii = np.matrix(([[4*EI/L,0,6*EI/L**2],
                       [0,EF/L,0],
                       [6*EI/L**2,0,12*EI/L**3]]))

  K_jj = np.matrix(([[4*EI/L,0,6*EI/L**2],
                       [0,EF/L,0],
                       [6*EI/L**2,0,12*EI/L**3]]))
  print('K_{}{}_ii ='.format(i,j))
  display(sym.Matrix(K_ii))

  K_ij = np.matrix(([[2*EI/L,0,6*EI/L**2],
                        [0,EF/L,0],
                        [6*EI/L**2,0,12*EI/L**3]]))

  print('K_{}{}_ij ='.format(i,j))
  display(sym.Matrix(K_ij))


  K1_ii = np.float64(K_ii+np.diag(spring_list.loc[i]))
  K1_jj = np.float64(K_jj+np.diag(spring_list.loc[j]))
  K1_ij = np.float64(K_ij)
  K1_ji = K1_ij

  K0 = np.vstack((np.hstack((K_ii,K_ij)),np.hstack((K_ij,K_jj))))
  K1 = np.vstack((np.hstack((K1_ii,K1_ij)),np.hstack((K1_ji,K1_jj))))
  K_lokal = K0-np.dot(np.dot(K0,np.linalg.inv(K1)),K0)
  print('K_{}{}_LOKAL ='.format(i,j))
  display(sym.Matrix(K_lokal))
  K_ii, K_ij, K_ji, K_jj =  K_lokal[0:3,0:3],K_lokal[0:3,3:6],K_lokal[3:6,0:3],K_lokal[3:6,3:6]

  #K_1 = np.diag(np.full((6, 6), 10**50))
  #K_1[np.]

  T2_i = np.matrix(([[1,0,0],
                       [0,-ssp.cosdg(beta),ssp.sindg(beta)],
                       [0,-ssp.sindg(beta),-ssp.cosdg(beta)]]))

  T2_j = np.matrix(([[1,0,0],
                       [0,ssp.cosdg(beta),-ssp.sindg(beta)],
                       [0,ssp.sindg(beta),ssp.cosdg(beta)]]))

  print('T_2_{} ='.format(ele))
  T_2 =  np.vstack((np.hstack((T2_i,np.zeros((3,3)))),np.hstack((np.zeros((3,3)),T2_j))))
  display(sym.Matrix(T_2))

  # Calculating FEM from distributed load
  p0_dst = np.transpose(np.matrix([-W_x*L_z**2/12+W_z*L_x**2/12,
                               W_x*L_x/2+W_z*L_z/2,
                               W_x*L_z/2+W_z*L_x/2,
                               W_x*L_x**2/12-W_z*L_x**2/12+Pl_M_j,
                              -W_x*L_x/2-W_z*L_z/2,
                              -W_x*L_z/2-W_z*L_x/2]))
  p0_indrgnms = p0_dst-np.dot(np.dot(K0,np.linalg.inv(K1)),p0_dst)

  # calculating P from deformation
  w_dfrm = np.transpose(np.hstack((deform_list.loc[i],deform_list.loc[j])))
  print('w_dfrm_{} ='.format(ele))
  print(w_dfrm)

  p0_dfrm = np.dot(np.dot(np.dot(T_2,K_lokal),np.transpose(T_2)),np.transpose(w_dfrm))
  p0 = p0_indrgnms+p0_dfrm
  p0_transf = p0

  p0_global[(i-1)*3] =     p0_transf[0,0]+p0_global[(i-1)*3]
  p0_global[((i-1)*3)+1] = p0_transf[0,1]+p0_global[((i-1)*3)+1]
  p0_global[((i-1)*3)+2] = p0_transf[0,2]+p0_global[((i-1)*3)+2]
  p0_global[(j-1)*3] =     p0_transf[0,3]+p0_global[(j-1)*3]
  p0_global[((j-1)*3)+1] = p0_transf[0,4]+p0_global[((j-1)*3)+1]
  p0_global[((j-1)*3)+2] = p0_transf[0,5]+p0_global[((j-1)*3)+2]

  print('―' * 50)


  K_global[3*(i-1):3*(i-1)+3,3*(i-1):3*(i-1)+3] = np.dot(np.dot(T2_i,K_ii),np.transpose(T2_i))+K_global[3*(i-1):3*(i-1)+3,3*(i-1):3*(i-1)+3]
  K_global[3*(i-1):3*(i-1)+3,3*(j-1):3*(j-1)+3] = np.dot(np.dot(T2_i,K_ij),np.transpose(T2_j))+K_global[3*(i-1):3*(i-1)+3,3*(j-1):3*(j-1)+3]
  K_global[3*(j-1):3*(j-1)+3,3*(i-1):3*(i-1)+3] = np.dot(np.dot(T2_j,K_ji),np.transpose(T2_i))+K_global[3*(j-1):3*(j-1)+3,3*(i-1):3*(i-1)+3]
  K_global[3*(j-1):3*(j-1)+3,3*(j-1):3*(j-1)+3] = np.dot(np.dot(T2_j,K_jj),np.transpose(T2_j))+K_global[3*(j-1):3*(j-1)+3,3*(j-1):3*(j-1)+3]


  display(sym.Matrix(K_global))
  display(sym.Matrix(p0_global))


  ### force vector
  #p0[i-1:i+2] = [-dstfr_list.loc[ele]['W_x']+dstfr_list.loc[ele]['W_z']+pntfr_list.loc[ele]['P_theta']]

##### ADDITIONAL CODE

P_global = q_global - p0_global

K_global[:3,:3],K_global[:3,3:6],K_global[3:6,:3],K_global[3:6,3:6] =   K_global[:3,:3]+K_star_11,K_global[:3,3:6]+K_star_12,K_global[3:6,:3]+K_star_21,K_global[3:6,3:6]+K_star_22
P_global[:3,:3],P_global[:3,3:6],P_global[3:6,:3],P_global[3:6,3:6] =   P_global[:3,:3]+P_star_11,P_global[:3,3:6]+P_star_12,P_global[3:6,:3]+P_star_21,P_global[3:6,3:6]+P_star_22

K_ii, K_ij, K_ji, K_jj =  K_lokal[0:3,0:3],K_lokal[0:3,3:6],K_lokal[3:6,0:3],K_lokal[3:6,3:6]

T2_i = np.matrix(([[1,0,0],
                    [0,-ssp.cosdg(270),ssp.sindg(270)],
                    [0,-ssp.sindg(270),-ssp.cosdg(270)]]))

T2_j = np.matrix(([[1,0,0],
                    [0,ssp.cosdg(270),-ssp.sindg(270)],
                    [0,ssp.sindg(270),ssp.cosdg(270)]]))


K_star_rotated_11,K_star_rotated_12,K_star_rotated_21,K_star_rotated_22 = np.dot(np.dot(T2_i,K_star_11),np.transpose(T2_i)),np.dot(np.dot(T2_i,K_star_11),np.transpose(T2_j)),np.dot(np.dot(T2_j,K_star_11),np.transpose(T2_i)),np.dot(np.dot(T2_j,K_star_11),np.transpose(T2_j))

P_star_rotated_11,P_star_rotated_12,P_star_rotated_21,P_star_rotated_22 = P_star_11,P_star_12,P_star_21,P_star_22
P_star_rotated_11[[1,2]],P_star_rotated_12[[1,2]],P_star_rotated_21[[1,2]],P_star_rotated_22[[1,2]] = P_star_rotated_11[[2,1]],P_star_rotated_12[[2,1]],P_star_rotated_21[[2,1]],P_star_rotated_22[[2,1]]

K_global[3:6,3:6],K_global[3:6,9:12],K_global[9:12,3:6],K_global[9:12,9:12] =   K_global[3:6,3:6]+K_star_rotated_11,K_global[3:6,9:12]+K_star_rotated_12,K_global[9:12,3:6]+K_star_rotated_21,K_global[9:12,9:12]+K_star_rotated_22
P_global[3:6,3:6],P_global[3:6,9:12],P_global[9:12,3:6],P_global[9:12,9:12] =   P_global[3:6,3:6]+P_star_rotated_11,P_global[3:6,9:12]+P_star_rotated_12,P_global[9:12,3:6]+P_star_rotated_21,P_global[9:12,9:12]+P_star_rotated_22



##### END OF ADDITIONAL CODE


## trimming the equation
trim_index = np.flatnonzero(rstrd)
K_global_trimmed = np.delete(np.delete(K_global,trim_index,0),trim_index,1)

#p0_global_trimmed = np.delete(p0_global,trim_index,0)
#q_global_trimmed = np.delete(q_global,trim_index,0)

P_global_trimmed = np.delete(P_global,trim_index,0)

d = np.linalg.solve(K_global_trimmed,P_global_trimmed)

'''
d_resized = d.reshape(d,(P_global.size,1))

d_full = np.zeros(())
for trim_i in trim_index:

  d_full = np.insert(d_resized, trim_i, 0)
'''
display(sym.Matrix(d))
print(d)

print('K_global_trimmed')


#D_i = np.dot(np.inverse(K11),Q1)-np.dot(np.dot(np.inverse(K11),K12),Dd)

display(sym.Matrix(K_star))

K_12_ii =


Matrix([
[500000.0,          0, 187500.0],
[       0, 12500000.0,        0],
[187500.0,          0,  93750.0]])

K_12_ij =


Matrix([
[250000.0,          0, 187500.0],
[       0, 12500000.0,        0],
[187500.0,          0,  93750.0]])

K_12_LOKAL =


Matrix([
[500000.0,          0, 187500.0, 250000.0,          0, 187500.0],
[       0, 12500000.0,        0,        0, 12500000.0,        0],
[187500.0,          0,  93750.0, 187500.0,          0,  93750.0],
[250000.0,          0, 187500.0, 500000.0,          0, 187500.0],
[       0, 12500000.0,        0,        0, 12500000.0,        0],
[187500.0,          0,  93750.0, 187500.0,          0,  93750.0]])

T_2_1 =


Matrix([
[1.0,    0,    0,   0,   0,   0],
[  0, -1.0,    0,   0,   0,   0],
[  0,    0, -1.0,   0,   0,   0],
[  0,    0,    0, 1.0,   0,   0],
[  0,    0,    0,   0, 1.0,   0],
[  0,    0,    0,   0,   0, 1.0]])

w_dfrm_1 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 500000.0,           0, -187500.0,  250000.0,           0, 187500.0, 0, 0, 0, 0, 0, 0],
[        0,  12500000.0,         0,         0, -12500000.0,        0, 0, 0, 0, 0, 0, 0],
[-187500.0,           0,   93750.0, -187500.0,           0, -93750.0, 0, 0, 0, 0, 0, 0],
[ 250000.0,           0, -187500.0,  500000.0,           0, 187500.0, 0, 0, 0, 0, 0, 0],
[        0, -12500000.0,         0,         0,  12500000.0,        0, 0, 0, 0, 0, 0, 0],
[ 187500.0,           0,  -93750.0,  187500.0,           0,  93750.0, 0, 0, 0, 0, 0, 0],
[        0,           0,         0,         0,           0,        0, 0, 0, 0, 0, 0, 0],
[        0,           0,         0,         0,           0,        0, 0, 0, 0, 0, 0, 0],
[        0,           0,         0,         0,           0,        0, 0, 0, 0, 0, 0, 0],
[        0,           0,         0,         0,           0,        0, 0, 0, 0, 0, 0, 0],
[        0,           0,         0,         0,           0,        0, 0, 0, 0, 0, 0, 0],
[        0, 

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_31_ii =


Matrix([
[666666.666666667,                0, 333333.333333333],
[               0, 16666666.6666667,                0],
[333333.333333333,                0, 222222.222222222]])

K_31_ij =


Matrix([
[333333.333333333,                0, 333333.333333333],
[               0, 16666666.6666667,                0],
[333333.333333333,                0, 222222.222222222]])

K_31_LOKAL =


Matrix([
[666666.666666667,                0, 333333.333333333, 333333.333333333,                0, 333333.333333333],
[               0, 16666666.6666667,                0,                0, 16666666.6666667,                0],
[333333.333333333,                0, 222222.222222222, 333333.333333333,                0, 222222.222222222],
[333333.333333333,                0, 333333.333333333, 666666.666666667,                0, 333333.333333333],
[               0, 16666666.6666667,                0,                0, 16666666.6666667,                0],
[333333.333333333,                0, 222222.222222222, 333333.333333333,                0, 222222.222222222]])

T_2_2 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_2 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 1166666.66666667,  333333.333333333,         -187500.0,  250000.0,           0, 187500.0,  333333.333333333, -333333.333333333,                 0, 0, 0, 0],
[ 333333.333333333,  12722222.2222222,                 0,         0, -12500000.0,        0,  333333.333333333, -222222.222222222,                 0, 0, 0, 0],
[        -187500.0,                 0,  16760416.6666667, -187500.0,           0, -93750.0,                 0,                 0, -16666666.6666667, 0, 0, 0],
[         250000.0,                 0,         -187500.0,  500000.0,           0, 187500.0,                 0,                 0,                 0, 0, 0, 0],
[                0,       -12500000.0,                 0,         0,  12500000.0,        0,                 0,                 0,                 0, 0, 0, 0],
[         187500.0,                 0,          -93750.0,  187500.0,           0,  93750.0,                 0,                 0,                 0, 0, 0, 0],
[ 333333.333333333,  333333.333333333

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_42_ii =


Matrix([
[666666.666666667,                0, 333333.333333333],
[               0, 16666666.6666667,                0],
[333333.333333333,                0, 222222.222222222]])

K_42_ij =


Matrix([
[333333.333333333,                0, 333333.333333333],
[               0, 16666666.6666667,                0],
[333333.333333333,                0, 222222.222222222]])

K_42_LOKAL =


Matrix([
[666666.666666667,                0, 333333.333333333, 333333.333333333,                0, 333333.333333333],
[               0, 16666666.6666667,                0,                0, 16666666.6666667,                0],
[333333.333333333,                0, 222222.222222222, 333333.333333333,                0, 222222.222222222],
[333333.333333333,                0, 333333.333333333, 666666.666666667,                0, 333333.333333333],
[               0, 16666666.6666667,                0,                0, 16666666.6666667,                0],
[333333.333333333,                0, 222222.222222222, 333333.333333333,                0, 222222.222222222]])

T_2_3 =


Matrix([
[1.0,   0,    0,   0,    0,   0],
[  0,   0, -1.0,   0,    0,   0],
[  0, 1.0,    0,   0,    0,   0],
[  0,   0,    0, 1.0,    0,   0],
[  0,   0,    0,   0,    0, 1.0],
[  0,   0,    0,   0, -1.0,   0]])

w_dfrm_3 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 1166666.66666667,  333333.333333333,         -187500.0,          250000.0,                 0,          187500.0,  333333.333333333, -333333.333333333,                 0,                 0,                 0,                 0],
[ 333333.333333333,  12722222.2222222,                 0,                 0,       -12500000.0,                 0,  333333.333333333, -222222.222222222,                 0,                 0,                 0,                 0],
[        -187500.0,                 0,  16760416.6666667,         -187500.0,                 0,          -93750.0,                 0,                 0, -16666666.6666667,                 0,                 0,                 0],
[         250000.0,                 0,         -187500.0,  1166666.66666667,  333333.333333333,          187500.0,                 0,                 0,                 0,  333333.333333333, -333333.333333333,                 0],
[                0,       -12500000.0,                 0,  333333.33333

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

K_34_ii =


Matrix([
[500000.0,          0, 187500.0],
[       0, 12500000.0,        0],
[187500.0,          0,  93750.0]])

K_34_ij =


Matrix([
[250000.0,          0, 187500.0],
[       0, 12500000.0,        0],
[187500.0,          0,  93750.0]])

K_34_LOKAL =


Matrix([
[500000.0,          0, 187500.0, 250000.0,          0, 187500.0],
[       0, 12500000.0,        0,        0, 12500000.0,        0],
[187500.0,          0,  93750.0, 187500.0,          0,  93750.0],
[250000.0,          0, 187500.0, 500000.0,          0, 187500.0],
[       0, 12500000.0,        0,        0, 12500000.0,        0],
[187500.0,          0,  93750.0, 187500.0,          0,  93750.0]])

T_2_4 =


Matrix([
[1.0,    0,    0,   0,   0,   0],
[  0, -1.0,    0,   0,   0,   0],
[  0,    0, -1.0,   0,   0,   0],
[  0,    0,    0, 1.0,   0,   0],
[  0,    0,    0,   0, 1.0,   0],
[  0,    0,    0,   0,   0, 1.0]])

w_dfrm_4 =
[0 0 0 0 0 0]
――――――――――――――――――――――――――――――――――――――――――――――――――


Matrix([
[ 1166666.66666667,  333333.333333333,         -187500.0,          250000.0,                 0,          187500.0,  333333.333333333, -333333.333333333,                 0,                 0,                 0,                 0],
[ 333333.333333333,  12722222.2222222,                 0,                 0,       -12500000.0,                 0,  333333.333333333, -222222.222222222,                 0,                 0,                 0,                 0],
[        -187500.0,                 0,  16760416.6666667,         -187500.0,                 0,          -93750.0,                 0,                 0, -16666666.6666667,                 0,                 0,                 0],
[         250000.0,                 0,         -187500.0,  1166666.66666667,  333333.333333333,          187500.0,                 0,                 0,                 0,  333333.333333333, -333333.333333333,                 0],
[                0,       -12500000.0,                 0,  333333.33333

Matrix([
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0],
[0]])

Matrix([
[   -5.658821539341e-5],
[ -9.93927236494969e-6],
[-0.000113476183764337],
[  6.33590257207667e-6],
[  9.78305012694619e-6],
[  -2.2323942147354e-5],
[-0.000131565311794287],
[  4.20893481981646e-6],
[-0.000131799926469542]])

[[-5.65882154e-05]
 [-9.93927236e-06]
 [-1.13476184e-04]
 [ 6.33590257e-06]
 [ 9.78305013e-06]
 [-2.23239421e-05]
 [-1.31565312e-04]
 [ 4.20893482e-06]
 [-1.31799926e-04]]
K_global_trimmed


Matrix([
[ 70800.0762002089,  -22713.348764161, -2960.96389401337, -41117.8188232464,  22713.3487641596,  2960.96389401337],
[ -22713.348764161,  11641.8866574482, -57.8102890519372,  22689.5411859788, -11641.8866574475,  57.8102890519378],
[-2960.96389401337, -57.8102890519378,  22556.4418412657, -3200.61014854414,  57.8102890518658, -22556.4418412671],
[-41117.8188232464,  22689.5411859788, -3200.61014854414,  70701.3844788207, -22689.5411859806,  3200.61014854413],
[ 22713.3487641596, -11641.8866574475,  57.8102890518644, -22689.5411859806,  11641.8866574487, -57.8102890518585],
[ 2960.96389401336,    57.81028905194, -22556.4418412671,  3200.61014854412, -57.8102890518557,  22556.4418412666]])

In [ ]:
d[1,0]

-4.973477003010496e-07

In [3]:
K12_1x1x = K_global[:3,:3]
K12_1x2x = K_global[:3,3:6]
K12_2x1x = K_global[3:6,:3]
K12_2x2x = K_global[3:6,3:6]

K31_3x3x = K_global[6:9,6:9]
K31_3x1x = K_global[6:9,:3]
K31_1x3x = K_global[:3,6:9]
K31_1x1x = K_global[:3,:3]

K42_4x4x = K_global[9:12,9:12]
K42_4x2x = K_global[9:12,3:6]
K42_2x4x = K_global[3:6,9:12]
K42_2x2x = K_global[3:6,3:6]

K34_3x3x = K_global[6:9,6:9]
K34_3x4x = K_global[6:9,9:12]
K34_4x3x = K_global[9:12,6:9]
K34_4x4x = K_global[9:12,9:12]

d_1x = [d[0,0],0,d[1,0]]
d_2x = [d[2,0],d[3,0],d[4,0]]
d_3x = [d[5,0],d[6,0],0]
d_4x = [d[7,0],d[8,0],0]

p0_1x = [P_global_trimmed[0,0],0,P_global_trimmed[1,0]]
p0_2x = [P_global_trimmed[2,0],P_global_trimmed[3,0],P_global_trimmed[4,0]]
p0_3x = [P_global_trimmed[5,0],P_global_trimmed[6,0],0]
p0_4x = [P_global_trimmed[7,0],P_global_trimmed[8,0],0]

P_global_trimmed

## çubuk 12, i=1,j=2

p12_1x = np.dot(K12_1x1x,d_1x)+np.dot(K12_1x2x,d_2x)+p0_1x
p12_2x = np.dot(K12_2x2x,d_2x)+np.dot(K12_2x1x,d_1x)+p0_2x

p12_1=np.dot(np.identity(3),np.transpose(p12_1x))
p12_2=np.dot(np.identity(3),np.transpose(p12_2x))

## çubuk 34, i=3,j=4

p34_3x = np.dot(K34_3x3x,d_3x)+np.dot(K34_3x4x,d_4x)+p0_3x
p34_4x = np.dot(K34_4x4x,d_4x)+np.dot(K34_4x3x,d_3x)+p0_4x

p34_3=np.dot(np.identity(3),np.transpose(p34_3x))
p34_4=np.dot(np.identity(3),np.transpose(p34_4x))

## çubuk 31, i=3,j=1

p31_3x = np.dot(K31_3x3x,d_3x)+np.dot(K31_3x1x,d_1x)+p0_3x
p31_1x = np.dot(K31_1x1x,d_1x)+np.dot(K31_1x3x,d_3x)+p0_1x

p31_3=np.dot(np.transpose(T2_i),np.transpose(p31_3x))
p31_1=np.dot(np.transpose(T2_j),np.transpose(p31_1x))

## çubuk 42, i=4,j=2

p42_4x = np.dot(K42_4x4x,d_4x)+np.dot(K42_4x2x,d_2x)+p0_4x
p42_2x = np.dot(K42_2x2x,d_2x)+np.dot(K42_2x4x,d_4x)+p0_2x

p42_4=np.dot(np.transpose(T2_i),np.transpose(p42_4x))
p42_2=np.dot(np.transpose(T2_j),np.transpose(p42_2x))

#p_1,p_2,p_3,p_4,p_5,p_3=p41_1+p12_1,p23_2,p34_3,p41_4+p54_4,p54_5,p23_3



In [4]:

print("Values are in local axis")
x= pd.DataFrame([
                 [p12_1[0],p12_1[1],p12_1[2],p12_2[0],p12_2[1],p12_2[2]],
                 [p34_3[0],p34_3[1],p34_3[2],p34_4[0],p34_4[1],p34_4[2]],
                 [p31_3[0,0],p31_3[0,1],p31_3[0,2],p31_1[0,0],p31_1[0,1],p31_1[0,2]],
                 [p42_4[0,0],p42_4[0,1],p42_4[0,2],p42_2[0,0],p42_2[0,1],p42_2[0,2]]],
                columns=['Msol','Nsol','Vsol','Msağ','Nsağ','Vsağ'],
                index=['Ç12','Ç34','Ç31','Ç42']
                )
#
x

Values are in local axis


Msol        Nsol         Vsol        Msağ        Nsağ        Vsağ
Ç12 -143.244101  -99.423557  -271.060366 -263.456214  121.579019  271.148345
Ç34   18.862738  -18.862738     3.396564   43.950995  -36.609934   -3.308584
Ç31   -1.052234  169.840279  1647.499081  -85.134357  291.562878    4.218566
Ç42    5.580986 -164.865364  1644.566397 -207.506835 -280.682210  156.542153

In [5]:
%%shell
jupyter nbconvert --to html "YapiSistHesabMatYon_Odev3.ipynb"

[NbConvertApp] Converting notebook YapiSistHesabMatYon_Odev3.ipynb to html
[NbConvertApp] Writing 946897 bytes to YapiSistHesabMatYon_Odev3.html
